### ISSUE TITLE
请问上传的音频等数据是存储在本地的吗？

### ISSUE THREAD

**Issue by Anbool** [mebtte/cicada#104]
是直接存储在本地的吗？还是支持上传到对象存储，如阿里云OSS或者腾讯云COS等，直接从CDN网络播放音频等。

**Comment by mebtte** [comment]
存储在参数指定的的 data 文件夹, 不支持上传到对象存储

**Comment by Anbool** [comment]
> 存储在参数指定的的 data 文件夹, 不支持上传到对象存储

如此的话，那存储的音频图片等数据受限于服务器的存储和带宽限制呢

**Comment by mebtte** [comment]
> 如此的话，那存储的音频图片等数据受限于服务器的存储和带宽限制呢

是的, 因为知了一开始的设计就是在小范围使用, 在数人同时使用的情况下低带宽也足够应付
