### ISSUE TITLE
非法的服务器地址

### ISSUE THREAD

**Issue by steveyu2** [mebtte/cicada#112]
最新版的v2
ngrok用了一会正常，然后就不行了，这个可能是ngrok的问题
不过局域网的好像也不行
https://215e-14-122-131-216.ngrok-free.app
![Screenshot_20231120_160105](https://github.com/mebtte/cicada/assets/26341956/113c3837-da11-4975-ba64-9c5efc7f7e0e)
局域网的情况
![Screenshot_20231120_160621](https://github.com/mebtte/cicada/assets/26341956/7f925852-8df3-444c-9da6-c9f20bc59b28)

**Comment by mebtte** [comment]
知了在 2.0.1 已经移除了服务器地址的校验, 请确认下是否使用最新版本 2.5.0
