### ISSUE TITLE
关于歌曲导入的数据处理

### ISSUE THREAD

**Issue by vaxl029** [mebtte/cicada#117]
> 先推荐个软件 [音乐标签](https://www.cnblogs.com/vinlxc/p/11347744.html) ，这个软件可以一键抓取各种标签存储到音乐文件自身上，包括 **知了** 现在需要的封面/歌词/发行时间等。一个音乐文件即全部，不再需要另外存储封面及歌词文件。

---

#### 前台上传与命令导入差异
- 前台上传包含标签的音乐文件时，有处理歌曲名/歌手/封面标签数据，歌词及发行时间未处理。P：选取完音乐文件后不点击创建，然后换一个音乐文件，歌曲名/歌手信息没有重新更新。
- 命令导入包含标签的音乐文件时，有处理歌曲名/歌手标签数据，封面/歌词/发行时间未处理。P-：没有处理封面，导入后的歌曲不会出现在"发现"菜单内。

#### 建议处理方式
- 无论前台上传还是命令导入，都优先提取歌曲文件内对应标签。例如封面标签有内容就直接提取到music_cover目录内，没有则不处理。

---

#### 几个与歌曲导入无关的建议
- 歌曲默认封面与歌手默认头像是相同的，换成不同的观感会好些。
- 前台删除歌曲时，没有物理删除文件。可以考虑做个回收站，二次确认后物理删除文件。
- 有的歌曲封面图很花，不适合做歌词背景。可以考虑做个淡色背景，或者把歌词字体调大/颜色调鲜艳些。

#### 最后，感谢您的付出，祝 **知了** 越来越好，越走越远。

**Comment by mebtte** [comment]
> 前台上传包含标签的音乐文件时，有处理歌曲名/歌手/封面标签数据，歌词及发行时间未处理。P：选取完音乐文件后不点击创建，然后换一个音乐文件，歌曲名/歌手信息没有重新更新。

这个处理逻辑是如果已经填入了相关信息(歌手/歌名)则不会自动填入, 避免了用户主动输入被替换的情况. 歌词和发行时间的话可以进行优化.

> 命令导入没有处理音乐标签的问题

可以优化

> 导入后的歌曲不会出现在"发现"菜单内。

发现菜单里的音乐需要封面, 歌手需要头像, 乐单需要封面才会出现

> 歌曲默认封面与歌手默认头像是相同的，换成不同的观感会好些。

这个可以优化, 但是目前没有设计资源

> 前台删除歌曲时，没有物理删除文件。可以考虑做个回收站，二次确认后物理删除文件。

有回收站功能, 不是删除的同时移入回收站, 而是每天的定时任务会扫描未关联音乐然后移入回收站

> 有的歌曲封面图很花，不适合做歌词背景。可以考虑做个淡色背景，或者把歌词字体调大/颜色调鲜艳些。

歌词的展示目前正在考虑改版, 新的形式还没有确定

**Comment by mebtte** [comment]
更正一下, 目前前端导入音乐是有处理歌词的
歌词没有实际导入的原因是大部分音乐标签中的歌词并不是 LRC 格式
而是单纯的文本, 从而无法实际录入

**Comment by mebtte** [comment]
2.6.0 已经更新
1. 前端导入现在已经会处理 year
2. 已经重构 `cicada import`, 从音乐标签获取数据而不是文件名
3. 默认歌手头像已经和音乐区分
4. 音乐标签歌词的问题, 目前绝大部分歌词都是纯文本而不是 LRC, 所以知了不再处理音乐标签中的歌词
