### ISSUE TITLE
How to import music in batches/如何批量导入音乐

### ISSUE THREAD

**Issue by JinBiLianShao** [mebtte/cicada#118]
只能一个个的上传，当音乐数量很多的情况下显得特别麻烦。You can only upload one by one, which is particularly troublesome when there are a lot of music.

**Comment by JinBiLianShao** [comment]
能不能增加批量上传的功能？

**Comment by JinBiLianShao** [comment]
1. 关于歌词，作者，封面等参数可以等批量上传后手动配置。
2. 歌曲名的配置可以通过上传歌曲文件名提取识别并配置歌曲名称

**Comment by mebtte** [comment]
> 能不能增加批量上传的功能？

可以通过[命令行批量上传](https://github.com/mebtte/cicada?tab=readme-ov-file#import-music)

**Comment by mebtte** [comment]
> 1. 关于歌词，作者，封面等参数可以等批量上传后手动配置。
> 2. 歌曲名的配置可以通过上传歌曲文件名提取识别并配置歌曲名称

1. 通过 `cicada import` 或者前端导入会自动处理音乐标签中歌名/歌手/封面/年份, 后续可以手动修改
2. 因为文件名格式不固定, 所以无法处理, 歌曲名称只能从音乐标签中获取
