### ISSUE TITLE
关于歌单歌曲播放顺序问题

### ISSUE THREAD

**Issue by steveyu2** [mebtte/cicada#121]
感谢这个项目，我有一直在用。
我在歌单里面，点击加入播放列表的按钮，好像没办法顺序播放。

https://github.com/mebtte/cicada/assets/26341956/8a8d83b4-8c41-4b3f-8fc5-390c27f71118

github上传的视频好像看不到，我上传到[网盘](https://mega.nz/file/qCIUzSSD#DnbfqzxjbV5_4mAlm0BFgmV1ctN5Ds3T7HDWoWcNuJg)了

**Comment by mebtte** [comment]
知了的播放逻辑是这样
按照播放队列(playqueue)中的顺序进行播放, 如果播放队列(playqueue)已经在队尾了, 那么就会从播放列表(playlist)中随机抽取一首进行播放
如果想要按照顺序播放, 可以通过插队的方式定制播放队列(playqueue)
<img width="550" alt="image" src="https://github.com/mebtte/cicada/assets/8120967/b4e3165a-7012-47ae-8ca6-e04ba6fc5288">
<img width="550" alt="image" src="https://github.com/mebtte/cicada/assets/8120967/a945967d-ccf4-442d-854d-308b1152593a">

**Comment by steveyu2** [comment]
感谢回复，如果需要按照歌单顺序播放的话，只能一个个点吗，后期考虑加循环歌单播放的功能吗

**Comment by mebtte** [comment]
目前只支持单个音乐操作, 循环歌单的话可能还需要考虑一下具体的方案
