### ISSUE TITLE
播放发生错误

### ISSUE THREAD

**Issue by iIlegalUser** [mebtte/cicada#125]
导入音乐后播放提示播放发生错误
![{544EFBBA-923F-4d8b-AE1F-D203D2719D63}](https://github.com/mebtte/cicada/assets/72731192/27053784-95ae-49d7-8866-5929f9943394)
日志如下，cicada.log是运行输出日志
[asset_upload_20240408.log](https://github.com/mebtte/cicada/files/14906673/asset_upload_20240408.log)
[cicada.log](https://github.com/mebtte/cicada/files/14907248/cicada.log)
[db_20240408.log](https://github.com/mebtte/cicada/files/14906680/db_20240408.log)

怀疑是音乐文件太大导致的，文件均为.flac格式，大小在20M左右

**Comment by mebtte** [comment]
应该跟大小没有关系, 从日志看请求音乐文件都是 206, 但是被中断了, 需要进一步排查原因

**Comment by iIlegalUser** [comment]
> 应该跟大小没有关系, 从日志看请求音乐文件都是 206, 但是被中断了, 需要进一步排查原因

重新上传了日志cicada.log，之前的有点问题，没有记录错误

**Comment by mebtte** [comment]
这看上去像是网络存在问题, 响应数据时连接已经被关闭了, 是不是用了 nginx 之类的代理工具

**Comment by iIlegalUser** [comment]
没有，是直接部署的。你可以在这个网站复现
http://47.97.216.88:18966/
账号密码均为cicada

**Comment by mebtte** [comment]
格式可能存在问题,  chrome 不支持播放, 但是 firefox 是支持的

**Comment by mebtte** [comment]
firefox 也是可以的

**Comment by iIlegalUser** [comment]
谢谢

**Comment by mebtte** [comment]
后续会在上传时检测是否支持播放, 不支持播放会给出提示

**Comment by mebtte** [comment]
[2.7.0](https://github.com/mebtte/cicada/releases/tag/2.7.0) PWA 创建音乐时会检查音乐文件能否被浏览器播放, 不支持的音乐文件无法上传.
