### ISSUE TITLE
请问打包指定平台的命令是啥?

### ISSUE THREAD

**Issue by Jonnyan404** [mebtte/cicada#18]
我在amd64的Linux下,如何打包出arm64的二进制包?

**Comment by Jonnyan404** [comment]
无奈,改了几个参数,加上了arm64. 
但依然是只生成x64平台的二进制~

**Comment by mebtte** [comment]
@Jonnyan404 因为 [pkg](https://www.npmjs.com/pkg) 和 sqlite 的限制, 暂时没有办法跨平台打包

这个我正在研究, 可能后续会支持

**Comment by Jonnyan404** [comment]
> @Jonnyan404 因为 [pkg](https://www.npmjs.com/pkg) 和 sqlite 的限制, 暂时没有办法跨平台打包
> 
> 这个我正在研究, 可能后续会支持

1. 能不能把邮箱验证改成可选配置,默认关闭?
2. 从配置文件获取一个默认管理员登录用户(或者内置一个管理员用户,登录上去以后再增删改)?

**Comment by mebtte** [comment]
@Jonnyan404 
1. 因为比较担心暴力破解密码, 所以采用的是邮箱验证码的登录方式, 登录有效期现在是 180 天, 所以使用登录验证码的机会很少
2. 这个已经支持了, 配置项里面的 [initialAdminEmail](https://github.com/mebtte/cicada/blob/master/docs/config/index.md#initialadminemail)

**Comment by Jonnyan404** [comment]
现在的邮箱认证,拦截一大半

> @Jonnyan404
> 
> 1. 因为比较担心暴力破解密码, 所以采用的是邮箱验证码的登录方式, 登录有效期现在是 180 天, 所以使用登录验证码的机会很少
> 2. 这个已经支持了, 配置项里面的 [initialAdminEmail](https://github.com/mebtte/cicada/blob/master/docs/config/index.md#initialadminemail)

这对于想体验部署的人来说,增加了复杂度.还是建议能多一个密码登录方式.

**Comment by mebtte** [comment]
@Jonnyan404 拦截一大半是什么意思, 指的是发送的邮箱验证码被用户邮箱当做垃圾邮件呢?
我现在用的是 126 的邮箱服务, 可以做到 100% 送达

如果是登录页面"垃圾邮件"提示的话, 那个只是个通用的提示, 实际上并没有判断放入垃圾邮箱

**Comment by Jonnyan404** [comment]
> @Jonnyan404 拦截一大半是什么意思, 指的是发送的邮箱验证码被用户邮箱当做垃圾邮件呢? 我现在用的是 126 的邮箱服务, 可以做到 100% 送达
> 
> 如果是登录页面"垃圾邮件"提示的话, 那个只是个通用的提示, 实际上并没有判断放入垃圾邮箱

我是指拦截了一大半想部署的人,比如QQ邮箱配置这个就很烦人,可能就因为这个原因,都不愿意尝试了.
而且安全本就是一把双刃剑,还有一部分人是不怎么在乎安全的,只要方便.

**Comment by mebtte** [comment]
@Jonnyan404 使用第三方邮箱的话其实也不复杂, 除了登录以外, 还有一些其他功能也依赖邮箱服务, 比如导出乐单, 所以的话邮箱服务也是必不可少的

此外, 使用密码登录的话我要研究一下, 毕竟有被暴力破解的安全性

**Comment by Jonnyan404** [comment]
> @Jonnyan404 使用第三方邮箱的话其实也不复杂, 除了登录以外, 还有一些其他功能也依赖邮箱服务, 比如导出乐单, 所以的话邮箱服务也是必不可少的
> 
> 此外, 使用密码登录的话我要研究一下, 毕竟有被暴力破解的安全性

可以在密码登录的时候,屏蔽一切依赖邮箱的服务,仅提示配置邮箱后,享受完整服务.

**Comment by mebtte** [comment]
> 

这个我想一下, 毕竟改动比较大

**Comment by Jonnyan404** [comment]
> > 
> 
> 这个我想一下, 毕竟改动比较大

那还有一个简单方式,在启动的时候,给默认管理员随机一个验证码(或者从配置文件取),用来登录.

**Comment by Jonnyan404** [comment]
至少能让人进去看看什么样子,即使部分功能不能使用.

**Comment by Jonnyan404** [comment]
![image](https://user-images.githubusercontent.com/20352705/209286610-dec9fdbb-a7f1-459c-a948-8cd22f3eaf3b.png)
我用arm机器构建出来的,一直是这个提示

**Comment by Jonnyan404** [comment]
![image](https://user-images.githubusercontent.com/20352705/209287040-c56e1e38-b6ac-4cb7-9370-cb4bbdefd54a.png)

**Comment by mebtte** [comment]
>  那还有一个简单方式,在启动的时候,给默认管理员随机一个验证码(或者从配置文件取),用来登录.

@Jonnyan404 可以把配置文件中的 mode 改成 development 这样就不会真的发送登录验证码, 登录验证码会在终端输出

**Comment by Jonnyan404** [comment]
> > 那还有一个简单方式,在启动的时候,给默认管理员随机一个验证码(或者从配置文件取),用来登录.
> > @Jonnyan404 可以把配置文件中的 mode 改成 development 这样就不会真的发送登录验证码, 登录验证码会在终端输出

OK,那就比较简单的解决登录问题了.

**Comment by Jonnyan404** [comment]
然后帮忙看一下,为啥arm打包出来的不可用?
如果我用`build.sh`来执行是下面的报错

```bash
node:internal/child_process:420
    throw errnoException(err, 'spawn');
    ^

Error: spawn Unknown system error -8
    at ChildProcess.spawn (node:internal/child_process:420:11)
    at spawn (node:child_process:733:9)
    at fabricate (/cicada/node_modules/pkg/lib-es5/fabricator.js:55:51)
    at fabricateTwice (/cicada/node_modules/pkg/lib-es5/fabricator.js:120:5)
    at MultiStream._queue (/cicada/node_modules/pkg/lib-es5/producer.js:266:68)
    at MultiStream._next (/cicada/node_modules/multistream/index.js:86:12)
    at Meter.onEnd (/cicada/node_modules/multistream/index.js:129:12)
    at Object.onceWrapper (node:events:627:28)
    at Meter.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1358:12) {
  errno: -8,
  code: 'Unknown system error -8',
  syscall: 'spawn'
}
```

**Comment by mebtte** [comment]
@Jonnyan404 可能是 arm64 和 aarch64 不兼容, 这个我得研究一下

**Comment by Jonnyan404** [comment]
> @Jonnyan404 可能是 arm64 和 aarch64 不兼容, 这个我得研究一下

```
AArch64 is the 64-bit state introduced in the Armv8-A architecture (https://en.wikipedia.org/wiki/ARM_architecture#ARMv8-A). The 32-bit state which is backwards compatible with Armv7-A and previous 32-bit Arm architectures is referred to as AArch32. Therefore the GNU triplet for the 64-bit ISA is aarch64. The Linux kernel community chose to call their port of the kernel to this architecture arm64 rather than aarch64, so that's where some of the arm64 usage comes from.

As far as I know the Apple backend for aarch64 was called arm64 whereas the LLVM community-developed backend was called aarch64 (as it is the canonical name for the 64-bit ISA) and later the two were merged and the backend now is called aarch64.

So AArch64 and ARM64 refer to the same thing.
```

来源: https://stackoverflow.com/questions/31851611/differences-between-arm64-and-aarch64

---

上面说这两个是一个意思.

**Comment by mebtte** [comment]
@Jonnyan404 抱歉, 我刚去看了 pkg 的[文档](https://github.com/vercel/pkg#targets), 应该是不支持 armv8, 只支持到 armv6/armv7

**Comment by Jonnyan404** [comment]
> 文档

其实可以简单理解 armv8 == arm64,也就是说是支持的

**Comment by mebtte** [comment]
@Jonnyan404 我看这里是这样写的
<img width="804" alt="image" src="https://user-images.githubusercontent.com/8120967/209292118-32b24fb2-8bf6-4631-beda-45c5e4fec923.png">

**Comment by Jonnyan404** [comment]
> @Jonnyan404 我看这里是这样写的 <img alt="image" width="804" src="https://user-images.githubusercontent.com/8120967/209292118-32b24fb2-8bf6-4631-beda-45c5e4fec923.png">

这里意思是向后兼容到  armv6/armv7,    那里不是有写支持  arm64  吗?

**Comment by mebtte** [comment]
@Jonnyan404 你试一下手动指定构建目标吧
修改项目根目录的 package.json 文件, 找到 pkg 字段, 添加 targets:
```json
"pkg": {
  "assets": [
    "pwa/**/*",
    "node_modules/**/*.node"
  ],
  "outputPath": "build",
  "targets": ["node16-linux-arm64"]
}
```
然后通过 `npm run build:current` 构建, 看一下是否可行

**Comment by Jonnyan404** [comment]
> @Jonnyan404 你试一下手动指定构建目标吧 修改项目根目录的 package.json 文件, 找到 pkg 字段, 添加 targets:
> 
> ```json
> "pkg": {
>   "assets": [
>     "pwa/**/*",
>     "node_modules/**/*.node"
>   ],
>   "outputPath": "build",
>   "targets": ["node16-linux-arm64"]
> }
> ```
> 
> 然后通过 `npm run build:current` 构建, 看一下是否可行

我擦,我知道什么情况了,因为我是在`alpine`里运行的,我拷贝到本机里是可以了.
`alpine`是不是需要额外配置什么?

**Comment by mebtte** [comment]
@Jonnyan404 alpine 这个我不是很懂, 但是 `npm run build:current` 的方式基本上是支持所有平台的, 但是构建出的产物也仅仅局限于当前平台运行

**Comment by Jonnyan404** [comment]
> 

我就是在 arm64的`alpine` docker镜像里构建出来的,Ubuntu本地是可以运行的.  但在构建环境里就是上面我发的图里的报错(not found).

**Comment by Jonnyan404** [comment]
> > 那还有一个简单方式,在启动的时候,给默认管理员随机一个验证码(或者从配置文件取),用来登录.
> 
> @Jonnyan404 可以把配置文件中的 mode 改成 development 这样就不会真的发送登录验证码, 登录验证码会在终端输出

我无法访问开发模式,开发模式的路由地址是什么?(`/`路径开发模式直接404,生产模式正常.)
还是说编译以后,没法使用开发模式?

**Comment by mebtte** [comment]
@Jonnyan404 开发模式需要手动执行一遍 `npm run build:pwa`, 构建出前端资源才能访问前端

**Comment by Jonnyan404** [comment]
> @Jonnyan404 开发模式需要手动执行一遍 `npm run build:pwa`, 构建出前端资源才能访问前端

OK,我明天试试.
完了,重新打包docker镜像.
然后就可以正式发docker镜像了

**Comment by Jonnyan404** [comment]
> @Jonnyan404 开发模式需要手动执行一遍 `npm run build:pwa`, 构建出前端资源才能访问前端

不对,我只有二进制文件了,我去哪儿run呢.
也就是开发模式,依赖源代码?
或者依赖哪些目录?

**Comment by Jonnyan404** [comment]
> > @Jonnyan404 开发模式需要手动执行一遍 `npm run build:pwa`, 构建出前端资源才能访问前端

 不对,我只有二进制文件了,我去哪儿run呢.
 也就是开发模式,依赖源代码? 
或者依赖哪些目录?（方便提取出来放到docker里）

---

以上问题换种问法:
1. 二进制能否共存开发和生产模式?
2. 如果能,如何解决上述开发模式缺失前端的问题?
3. 如果不能,开发模式的完整运行流程命令是什么?

**Comment by Jonnyan404** [comment]
生产模式: `参数错误(#1001)` 是什么意思?

**Comment by mebtte** [comment]
@Jonnyan404 你是怎么打包以及运行的 还有配置文件是怎样 我看看

**Comment by mebtte** [comment]
> 生产模式: `参数错误(#1001)` 是什么意思?

这个可以在控制台看一下是哪个接口以及参数吗？

**Comment by Jonnyan404** [comment]
> 

https://music.mrdoc.fun/   地址是这个,你看看的

**Comment by Jonnyan404** [comment]
> @Jonnyan404 你是怎么打包以及运行的 还有配置文件是怎样 我看看

打包完全按照你这个步骤<https://github.com/mebtte/cicada/blob/master/docs/build/index.md>

**Comment by Jonnyan404** [comment]
> @Jonnyan404 你是怎么打包以及运行的 还有配置文件是怎样 我看看

![image](https://user-images.githubusercontent.com/20352705/209421356-a9d3832e-ba99-4246-9c4d-930365f9990c.png)

**Comment by Jonnyan404** [comment]
> @Jonnyan404 你是怎么打包以及运行的 还有配置文件是怎样 我看看

我试了你release里的预构建版本,m1下测试,一样的报错(参数错误[1001])..... 关键这个错误,前台后台没有任何错误日志 /大写的尴尬  
我感觉可能你这不支持QQ的smtp把~~~
我没别的邮箱,所以没测试别的邮箱...

**Comment by Jonnyan404** [comment]
这就是邮箱认证的弊端,有任何问题,直接连门都进不去😅

**Comment by Jonnyan404** [comment]
为了测试,我专门去注册了一个126邮箱,还是 `参数错误[井1001]`,
请楼主自行尝试 `release` 里的程序,能否正常使用把.
顺带排查和修复一下的.谢谢!

**Comment by Jonnyan404** [comment]
> 为了测试,我专门去注册了一个126邮箱,还是 `参数错误[井1001]`, 请楼主自行尝试 `release` 里的程序,能否正常使用把. 顺带排查和修复一下的.谢谢!

卧槽  我太难了,终于成功一个,用release里的预构建版本在amd64的Ubuntu下. 
同样的配置文件,在别的机器上死活参数错误❎,我实在是不能理解,这部署成本也太高了....

**Comment by Jonnyan404** [comment]
同时感谢楼主前面的耐心解答.

**Comment by Jonnyan404** [comment]
最后再补充一点信息:
1. docker里的程序在实体机器上没问题,可以排除编译的程序问题.
2. 只有在docker里才会在邮件环节出现(参数错误)
3. docker里nodemailer需要使用环境变量的方式载入邮件相关配置,我怀疑从配置文件读取的变量值改变了

--- 
那么问题就是,我们的程序支持从环境变量读取邮件相关配置吗?

**Comment by mebtte** [comment]
@Jonnyan404 参数错误的可以看一下日志
`data --> logs` 里面的 server_error

P.S. 这几天感染 没怎么关注 github 回复有点慢

**Comment by Jonnyan404** [comment]
> @Jonnyan404 参数错误的可以看一下日志 `data --> logs` 里面的 server_error
> 
> P.S. 这几天感染 没怎么关注 github 回复有点慢

没关系,你注意照顾身体,等身体好了再说.
不急,至少Linux下的二进制是可用的.

---

日志文件夹下的所有日志我都看过了,没有任何错误日志,需要在docker里调试了,可是我现在还不会.
目前怀疑问题在 `nodemailer` 上,我Google看到有很多 `nodemail` 在物理机上正常,但在docker里不行的例子.
但我解决不了,得等你康复以后看看了

**Comment by mebtte** [comment]
应该是参数错误的没加日志 我加一下吧 更好分析一点

**Comment by Jonnyan404** [comment]
> 应该是参数错误的没加日志 我加一下吧 更好分析一点

最好能把从配置文件读取到的变量值都打印一下,我看到有说docker里把变量值转义多了标点符号.

**Comment by mebtte** [comment]
有可能是 docker 的 dns 问题
https://stackoverflow.com/questions/45370428/nodemailer-with-docker

**Comment by Jonnyan404** [comment]
> 有可能是 docker 的 dns 问题 https://stackoverflow.com/questions/45370428/nodemailer-with-docker

我在容器里 telnet 了 smtp 的465端口是通的

**Comment by Jonnyan404** [comment]
https://stackoverflow.com/questions/61771392/nodemailer-cannot-send-emails-to-stmp-server-if-running-within-docker-container

跟这个描述的情况很相似

**Comment by mebtte** [comment]
@Jonnyan404 我 review 了一下代码 如果报参数错误的话是因为邮箱不存在 也就是用户没有被创建
![image](https://user-images.githubusercontent.com/8120967/209442267-df398ac9-8021-4b6c-add6-a180ce50e727.png)

**Comment by mebtte** [comment]
发不出邮件应该也不是 nodemailer 的问题 而是 docker 环境变量映射的问题 你可以试一下映射配置文件而不是环境变量

**Comment by Jonnyan404** [comment]
> @Jonnyan404 我 review 了一下代码 如果报参数错误的话是因为邮箱不存在 也就是用户没有被创建 ![image](https://user-images.githubusercontent.com/8120967/209442267-df398ac9-8021-4b6c-add6-a180ce50e727.png)

确实如你所说,是用户不存在的问题,折腾一天多,原因在于: 只要首次的登录邮箱未正确设置,后续改配置文件也不会重新生成,只能删库来触发重新生成.

**所以建议配置文件存在`initialAdminEmail`变量时,能在每次程序重启时覆盖数据库里的值.**

**Comment by mebtte** [comment]
initialAdminEmail 就是作为第一个管理员用户的 如果你不想要这个用户了 你可以先用这个用户登录 然后创建新的管理员用户 旧的管理员用户就不用管了 后续会增加删除用户的功能 就可以删除了

**Comment by Jonnyan404** [comment]
> initialAdminEmail 就是作为第一个管理员用户的 如果你不想要这个用户了 你可以先用这个用户登录 然后创建新的管理员用户 旧的管理员用户就不用管了 后续会增加删除用户的功能 就可以删除了

问题就出在这里,我登不上去啊,要能登上去,也不会卡昨天和前天两天时间了.
因为一开始的邮箱就给的是错误值,然后以为配置文件改对了,就好了,谁知道那个参数是一次性的....

**Comment by mebtte** [comment]
用 sqlite 打开 db 文件手动修改, user 表
或者把 db 删了, 重新启动会重新生成

**Comment by Jonnyan404** [comment]
,> 用 sqlite 打开 db 文件手动修改, user 表 或者把 db 删了, 重新启动会重新生成

那谁一开始就知道是这个问题呢,配上玄之又玄的错误提示,这不是一个好的设计,缺乏容错性.

**Comment by greek-zzf** [comment]
> ,> 用 sqlite 打开 db 文件手动修改, user 表或把 db 删了, 重新启动会重新生成
> 
> 那谁一开始就知道是这个问题呢，配上玄之又玄的错误提示，这不是一个好的设计，缺少错误。

是的，建议优化一下。没看到这个 issure 我估计也要折腾一两天。

**Comment by mebtte** [comment]
@greek-zzf 已经优化了, 用户不存在会正确地报错"用户不存在"
