### ISSUE TITLE
建议上docker

### ISSUE THREAD

**Issue by shelken** [mebtte/cicada#19]

**Comment by mebtte** [comment]
@shelken 目前我还对 docker 不熟悉, 后面的话添加 docker 镜像的

**Comment by Jonnyan404** [comment]
别急,等一下,就给你上docker

**Comment by mebtte** [comment]
@Jonnyan404 上 docker 的话跨平台的问题要解决一下

**Comment by Jonnyan404** [comment]
> @Jonnyan404 上 docker 的话跨平台的问题要解决一下

我那个issue就是为了解决这个问题的,不过只打算支持 amd64和arm64.

**Comment by Jonnyan404** [comment]
~https://hub.docker.com/r/jonnyan404/cicada~

---
我这个有问题,建议用楼主的预构建版本.

**Comment by Jonnyan404** [comment]
> https://hub.docker.com/r/jonnyan404/cicada
> 
> 生产模式已可用(注意修改配置文件), 目前开发模式还有点问题,要等开发者回复以后再优化.

生产模式可能也有问题,各位试试,反馈一下...  
我试过QQ的smtp不行

**Comment by eaglexiang** [comment]
建议部署示例里单独映射配置目录和音乐目录

**Comment by mebtte** [comment]
已添加 docker 镜像, https://github.com/mebtte/cicada#docker
