### ISSUE TITLE
首先感谢作者贡献~~~

### ISSUE THREAD

**Issue by chao325** [mebtte/cicada#26]
刚搭建好，想了解下添加音乐是 通过本地文件添加吗？还是....

**Comment by mebtte** [comment]
添加本地音乐

**Comment by chao325** [comment]
> 添加本地音乐

谢谢小咪对社区的贡献，非常感谢！还有个问题。我现在都就绪了，音乐也加了，至于要做成MacOS PC 移动端 轻应用就得靠PWA吗？？这方面的教程是不是直接去了解官方的PWA就可以了？还是得等你出一个适合咱们现在这个系统的PWA教程？

**Comment by mebtte** [comment]
PWA 是浏览器提供的功能, 直接使用就好了, 当前 Chrome 支持的比较好

**Comment by chao325** [comment]
> PWA 是浏览器提供的功能, 直接使用就好了, 当前 Chrome 支持的比较好

谢谢
