### ISSUE TITLE
建议规划一下 roadmap 方便社区开发者提交贡献

### ISSUE THREAD

**Issue by peevs4fun** [mebtte/cicada#30]
看到作者有后续的产品开发计划，建议规划一下做成 roadmap 方便社区提交贡献。感觉等后续提供 docker 部署之后，会有很多用户。自建音乐 server 在当前的环境下应该是挺多人需要的。至少那群玩 nas 的应该都有需求。

**Comment by mebtte** [comment]
暂时没有啥 roadmap, 都是想到什么做什么

**Comment by CodeByZack** [comment]
歌曲上传没有判断重复么。
![7c1509ba4a810699c7bbbdb3f159e2ab](https://user-images.githubusercontent.com/17472882/211745396-42714fb8-9efc-4e1f-939e-c676d736365a.png)

**Comment by mebtte** [comment]
不会做判断, 因为一个歌曲可能会有多个版本

**Comment by mebtte** [comment]
@CodeByZack 不会做判断, 因为一个歌曲可能会有多个版本, 可以通过别名区分

**Comment by mebtte** [comment]
roadmap: https://github.com/mebtte/cicada#roadmap
