### ISSUE TITLE
登录服务器错误是为啥？

### ISSUE THREAD

**Issue by 1197925584** [mebtte/cicada#33]

**Comment by mebtte** [comment]
详细描述一下或者带上日志/截图

**Comment by 1197925584** [comment]
{"code":1000,"message":"服务器错误"}
![1672810832865](https://user-images.githubusercontent.com/66343675/210491413-d26af4a5-c22d-4118-91b4-220d16df53c2.jpg)
![image](https://user-images.githubusercontent.com/66343675/210491543-2d152ed7-9264-441a-9e18-edee90e23ce0.png)

**Comment by mebtte** [comment]
连接不上邮件服务器, 可以用系统自带的邮件应用检查一下邮箱配置看看正不正确

**Comment by 1197925584** [comment]
需要自己有一个邮箱系统？

**Comment by mebtte** [comment]
可以用自己的, 但是一般推荐使用第三方的, 比如 QQ/163/126 这些

**Comment by 1197925584** [comment]
如果我想用QQ邮箱，那我的emailHost要怎么配置？

**Comment by mebtte** [comment]
qq 的发件服务器是 smtp.qq.com

**Comment by 1197925584** [comment]
可以了，但问题是我没歌

**Comment by mebtte** [comment]
知了只提供服务, 内容的话涉及到版权问题需要自己收集
