### ISSUE TITLE
创建音乐

### ISSUE THREAD

**Issue by hemycoo** [mebtte/cicada#34]
1 通过创建音乐来添加，一首一首的太慢了，是否可以通过扫描特定的文件夹来添加音乐
2 创建音乐后，文件名字变了，根据大小来看，还对音乐文件进行了压缩，这应该也是不可取的吧？
3 一般情况下，音乐文件里面包含了歌手，专辑等信息，可以通过扫描音乐文件的时候生成这些信息
4 最好可以选择 mysql 等数据库来管理用户信息
5 用户最好也可以用管理员账户来管理，并可以用密码登录最舒服

**Comment by mebtte** [comment]
1. 后面会提供 API 文档, 可以通过脚本批量添加音乐
2. 标准音质会自动压缩, 更好地保存和网络传输, 无损音质不会进行压缩
3. 没有统一标准所以没有办法实现
4. 使用 sqlite3 可以减少运行依赖
5. 用户管理的入口在设置页面, 使用验证码登录是为了保证安全, 一次登录有效期现在是半年, 基本登录后就不需要登录验证码了

**Comment by RedCatJump** [comment]
3.我其实比较好奇，其实通过mp3tag可以统一音乐的命名标准，也希望开发者考虑批量上传并自动读取tag，不然几千首音乐没法管理。

**Comment by mebtte** [comment]
如果有统一的命名方式的话是可以通过脚本导入的, 这个我可以研究一下

**Comment by CodeByZack** [comment]
大佬，脚本批量添加音乐，这个什么时候能出哇。
@mebtte

**Comment by mebtte** [comment]
@CodeByZack 这个我要研究一下 还不确定

**Comment by CodeByZack** [comment]
@mebtte 最近换到navidrome了，感觉可以参考一下这些软件的添加音乐方式，都是扫描本地文件，然后入库。
对于自建音乐服务来说，扫描本地文件确实比手动添加维护的号，大佬可以考虑一下。

**Comment by mebtte** [comment]
> @mebtte 最近换到navidrome了，感觉可以参考一下这些软件的添加音乐方式，都是扫描本地文件，然后入库。 对于自建音乐服务来说，扫描本地文件确实比手动添加维护的号，大佬可以考虑一下。

我研究了一下 Navidrome, 跟知了不一样的是, Navidrome 更像是一个带播放功能的网盘, 很多功能没有支持, 比如多用户/编辑封面等等都不支持

当然, 目前知了通过手动创建音乐的方式导入确实很麻烦, 后续会添加更加方便的导入方式

**Comment by mebtte** [comment]
[0.73.0](https://github.com/mebtte/cicada/releases/tag/0.73.0) 已添加 `cicada import` 命令导入现有音乐目录/音乐文件, 更多请查看 [README](https://github.com/mebtte/cicada#%E5%AF%BC%E5%85%A5%E9%9F%B3%E4%B9%90)
