### ISSUE TITLE
docker 部署后状态一直 Restarting

### ISSUE THREAD

**Issue by Lyunvy** [mebtte/cicada#39]
https://github.com/mebtte/cicada/blob/6bdd0f2c0f4183d72dbb0d43290539035eb7e679/readme.md?plain=1#L57

这个命令意思是不是要把宿主机 `$HOME/cicada-config.json` 这个文件映射到容器的 `/config.json` 文件呀，但 `docker run` 后 `$HOME` 下生成的是一个名为 `cicada-config.json` 的文件夹，配置文件放哪呀，不知道是不是因为没有配置文件，容器的状态也一直 `Restarting`。

**Comment by Lyunvy** [comment]
好吧，可能是因为镜像不对
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by mebtte** [comment]
暂时只提供 amd64 的镜像, arm 需要自己构建二进制包以及 docker 镜像
