### ISSUE TITLE
用户不存在 （#1025）

### ISSUE THREAD

**Issue by Yochi-84** [mebtte/cicada#43]
用的 docker，有配置 initialAdminEmail 了，一直显示用户不存在 （#1025）， Inspect 没报错

看过[这段](https://github.com/mebtte/cicada/issues/18#issuecomment-1364647134)了，應該是 initialAdminEmail 一開始有设置錯，所以我現在應該幹啥?已經刪過 Container 重建了

所以 initialAdminEmail 通常会跟 emailUser 一样吧？ 有理解错吗？

**Comment by mebtte** [comment]
@Yochi-84 `initialAdminEmail` 指的是管理员账号, 也就是你用来登录的账号
`emailUser` 是发信邮箱账号, 用来发送邮件的, 可以与 `initialAdminEmail` 一样, 也可以不一样

`initialAdminEmail` 只会在首次运行生成管理员账号, 后续修改是不会生效的
如果 `initialAdminEmail` 一开始设置错了, 可以删除知了的数据目录, 重新运行知了会再次生成新的数据目录

**Comment by Yochi-84** [comment]
@mebtte  搞懂了，把 cicada-data 删了就能重来了
