### ISSUE TITLE
不用邮箱验证的话，能本地用吗

### ISSUE THREAD

**Issue by wangkingsten** [mebtte/cicada#45]
不用邮箱验证的话，能本地用吗

**Comment by mebtte** [comment]
可以本地起服务本地用

**Comment by mebtte** [comment]
现已废弃邮箱验证码的方式, 采用账号密码的方式进行登录

**Comment by wangkingsten** [comment]
> 现已废弃邮箱验证码的方式, 采用账号密码的方式进行登录
thanks

**Comment by wangkingsten** [comment]
docker教程中的端口映射有错误
还有就是一直提示“非法的服务器地址”

**Comment by mebtte** [comment]
> docker教程中的端口映射有错误

这个已修正

> 还有就是一直提示“非法的服务器地址”

输入的内容是什么, 我验证一下正则

**Comment by wangkingsten** [comment]
docker run \
  -d \
  --restart=always \
  -p 8000:**80** \    刚刚查看，这里还是冲突状态
  -v <data>:/data \
  --name cicada \
  mebtte/cicada:v2 \
  start --port **8000** --data /data



我用的内网地址 192.168.3.123:8000
出现 非法的服务器地址
我修改本地的HOST用域名进去了
管理员昵称无法修改
刚在上传歌曲的时候，需要选择歌手，似乎是要从服务器获取歌手？
看起来这并不是一个纯本地的播放器

**Comment by mebtte** [comment]
> 我用的内网地址 192.168.3.123:8000
出现 非法的服务器地址

我看下正则

> 管理员昵称无法修改

管理员昵称在自己的资料修改
<img width="926" alt="image" src="https://github.com/mebtte/cicada/assets/8120967/d8d9376b-9fa2-4a9e-b66d-e346d40f0599">


> 刚在上传歌曲的时候，需要选择歌手，似乎是要从服务器获取歌手？

歌手是自己创建的, 点击"找不到歌手"就可以创建了
<img width="926" alt="image" src="https://github.com/mebtte/cicada/assets/8120967/2edfbd06-f9c8-4377-a98e-1c787cb7683e">
