### ISSUE TITLE
docker版支持cicada import命令吗？ 我运行都是找不到 cicada 命令

### ISSUE THREAD

**Issue by 59814** [mebtte/cicada#46]

**Comment by mebtte** [comment]
docker 镜像 cicada 位于 `/cicada`, 可以像这样使用:
```sh
/cicada import ...
```

**Comment by mebtte** [comment]
@59814 从 [0.73.1](https://github.com/mebtte/cicada/releases/tag/0.73.1) 开始, docker 镜像 `cicada` 已移动到 `/usr/bin/`, 可以直接使用 `cicada` 命令了
