### ISSUE TITLE
不安装PWA不能自动播放吗？

### ISSUE THREAD

**Issue by 59814** [mebtte/cicada#50]
我电脑用浏览器在后台播放一首之后就提示Cannot read properties of undefined (reading 'open')
还有不支持调音量吗？只有设置里面的相对系统音量吗？
![image](https://user-images.githubusercontent.com/110796707/221497197-de4aab2e-2f9c-4a0e-851f-3eab29849db0.png)

**Comment by mebtte** [comment]
1. 试一下升级浏览器版本, 部分老旧浏览器不支持一些高级 API 从而导致报错
2. 自动播放的问题同样试一下升级一下浏览版本
3. 浏览器不支持调剂系统音量, 只能调节相对系统音量(据我所知, 桌面 APP 也不能)

**Comment by 59814** [comment]
用的是Chrome 版本 110.0.5481.178（正式版本） （64 位） 提示是最新版呀，火狐也试过了...

**Comment by 59814** [comment]
大佬，你都是安装在哪里的呢？ 我安装在威联通的docker上，win电脑跟ios的网页用起来都很不方便，你的使用的设备是哪些呢？UI真的是用起来最好看的了，太喜欢了，但是折腾了半天感觉都用不了，郁闷

**Comment by mebtte** [comment]
> 用的是Chrome 版本 110.0.5481.178（正式版本） （64 位） 提示是最新版呀，火狐也试过了...

这个的话我要看一下, 确实没碰到过这个报错

**Comment by mebtte** [comment]
> 大佬，你都是安装在哪里的呢？ 我安装在威联通的docker上，win电脑跟ios的网页用起来都很不方便，你的使用的设备是哪些呢？UI真的是用起来最好看的了，太喜欢了，但是折腾了半天感觉都用不了，郁闷

我用的是 macOS Chrome, 手机是三星 Chrome

**Comment by mebtte** [comment]
> > 用的是Chrome 版本 110.0.5481.178（正式版本） （64 位） 提示是最新版呀，火狐也试过了...
> 
> 这个的话我要看一下, 确实没碰到过这个报错

这个你能把浏览器控制台的报错截一下?

**Comment by 59814** [comment]
> > > 用的是Chrome 版本 110.0.5481.178（正式版本） （64 位） 提示是最新版呀，火狐也试过了...
> > 
> > 
> > 这个的话我要看一下, 确实没碰到过这个报错
> 
> 这个你能把浏览器控制台的报错截一下?

浏览器的报错在哪里？ F12？

**Comment by 59814** [comment]
![image](https://user-images.githubusercontent.com/110796707/221562796-f22119a9-a086-4816-bc18-ade712ae6ef8.png)
是这个吗？

**Comment by mebtte** [comment]
@59814 你是怎么操作导致报错的, 或者安装了什么特殊的插件吗?

**Comment by 59814** [comment]
> 

全屏玩游戏，网页开着听歌，一首歌播放完之后就这样了，插件就一个deepl的翻译插件。

**Comment by mebtte** [comment]
> 全屏玩游戏，网页开着听歌，一首歌播放完之后就这样了，插件就一个deepl的翻译插件。

我先看一下, 暂时还没有头绪

**Comment by 59814** [comment]
> > 全屏玩游戏，网页开着听歌，一首歌播放完之后就这样了，插件就一个deepl的翻译插件。
> 
> 我先看一下, 暂时还没有头绪

这方面我安装了SSL证书后正常了，应该是有HTTPS之后PWA可以用了，
浏览器不支持调剂系统音量, 只能调节相对系统音量，这个能把调节相对系统音量的按钮放到外面吗？就是调节上一首下一首的地方，这样就不用为了调节个音量还要退回到设置哪里调节了

**Comment by mebtte** [comment]
@59814 我大概知道为什么会崩溃了 晚点发个修复版本

音量调节是个不常用的操作, 所以放到设置里面
而且在窄宽度的情况下, 控制区也不够足够的区域放置音量控制

**Comment by mebtte** [comment]
[0.74.0](https://github.com/mebtte/cicada/releases/tag/0.74.0) 已解决该问题
