### ISSUE TITLE
安装教程能详细一点吗？

### ISSUE THREAD

**Issue by guxinjian666** [mebtte/cicada#84]
你好，安装教程能再纤细一点吗？我尝试安装在云主机上，多次尝试仍未成功。linux的安装教程能再详细一点吗？比如  https://www.navidrome.org/docs/installation/linux/

**Comment by mebtte** [comment]
是哪一步有问题? 知了提供的是二进制包, 不需要安装额外依赖, 在 release 下载对应的包解压就可以直接运行, Docker 也是拉去对应镜像即可

**Comment by guxinjian666** [comment]
./cicada start -c config.json
-bash: ./cicada: No such file or directory

**Comment by guxinjian666** [comment]
安装教程我实在看不明白，请指教：
1.我下载的压缩软件，是要上传到根目录还是要自建目录里
2.config.json 是建在根目录还是建在自建目录

**Comment by mebtte** [comment]
> ./cicada start -c config.json -bash: ./cicada: No such file or directory

解压后不一定名为 `cicada`, 以 `1.5.0` linux 为例, 解压后名为 `cicada-linux`, 所以应该是 `cicada-linux start -c config.json`, 当然也可以重命名为 `cicada`

> 安装教程我实在看不明白，请指教： 1.我下载的压缩软件，是要上传到根目录还是要自建目录里 2.config.json 是建在根目录还是建在自建目录

这个是文件路径的知识, 二进制包和配置文件不关心所在的位置, 只要运行用户有权限执行二进制包和读取配置文件就可以

```sh
# 绝对路径
/path_to/cicada start -c /path_to/config.json

# 相对路径
./path_to/cicada start -c ./path_to/config.json
```

**Comment by guxinjian666** [comment]
感谢指教，已成功安装！有个小建议，默认安装在用户名字目录，如果可以指定安装目录就更好了。

**Comment by mebtte** [comment]
> 感谢指教，已成功安装！有个小建议，默认安装在用户名字目录，如果可以指定安装目录就更好了。

安装目录指的是什么? `cicada` 是一个二进制文件, 可以放在任何目录

**Comment by ferocknew** [comment]
docker 提示：

? Please enter the first user email: ? Please enter the first user email: ? Please enter the first user email: ? Please enter the first user email: ? Please enter the first user email: ? Please enter the first user email: ? Please%

**Comment by mebtte** [comment]
@ferocknew 
![image](https://github.com/mebtte/cicada/assets/8120967/3c5562c6-5d11-4ced-bf89-7e6812a857f3)

**Comment by ferocknew** [comment]
https://github.com/mebtte/cicada/blob/master/docs/config/index.md#firstUserEmail

404

firstUserEmail how configure ???

**Comment by ferocknew** [comment]
<img width="406" alt="image" src="https://github.com/mebtte/cicada/assets/2178683/8ccfc69a-4cea-45c5-8c43-88a3a54b523b">


一只提示错误

**Comment by ferocknew** [comment]
<img width="195" alt="image" src="https://github.com/mebtte/cicada/assets/2178683/e2fe4f2d-7bc3-4b06-8ca0-fd66e3eace91">

**Comment by mebtte** [comment]
> https://github.com/mebtte/cicada/blob/master/docs/config/index.md#firstUserEmail
> 
> 404
> 
> firstUserEmail how configure ???

Create a config file and map it to the container

**Comment by mebtte** [comment]
> <img alt="image" width="195" src="https://user-images.githubusercontent.com/2178683/265208947-e2fe4f2d-7bc3-4b06-8ca0-fd66e3eace91.png">

请贴一下错误日志, 位与数据目录下的 log 目录

**Comment by ferocknew** [comment]
[14:31:17.602] catch error by catcher
Error: Invalid login: 535 Login Fail. Please enter your authorization code to login. More information in http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256
    at SMTPConnection._formatError (/snapshot/cicada/node_modules/nodemailer/lib/smtp-connection/index.js:790:19)
    at SMTPConnection._actionAUTHComplete (/snapshot/cicada/node_modules/nodemailer/lib/smtp-connection/index.js:1548:34)
    at SMTPConnection.<anonymous> (/snapshot/cicada/node_modules/nodemailer/lib/smtp-connection/index.js:546:26)
    at SMTPConnection._processResponse (/snapshot/cicada/node_modules/nodemailer/lib/smtp-connection/index.js:953:20)
    at SMTPConnection._onData (/snapshot/cicada/node_modules/nodemailer/lib/smtp-connection/index.js:755:14)
    at TLSSocket.<anonymous> (/snapshot/cicada/node_modules/nodemailer/lib/smtp-connection/index.js:193:44)
    at TLSSocket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)




一定要配置 qq 邮箱和对应的密码？为什么使用必须登录 qq 邮箱？

**Comment by mebtte** [comment]
> [14:31:17.602] catch error by catcher Error: Invalid login: 535 Login Fail. Please enter your authorization code to login. More information in http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256 at SMTPConnection._formatError (/snapshot/cicada/node_modules/nodemailer/lib/smtp-connection/index.js:790:19) at SMTPConnection._actionAUTHComplete (/snapshot/cicada/node_modules/nodemailer/lib/smtp-connection/index.js:1548:34) at SMTPConnection. (/snapshot/cicada/node_modules/nodemailer/lib/smtp-connection/index.js:546:26) at SMTPConnection._processResponse (/snapshot/cicada/node_modules/nodemailer/lib/smtp-connection/index.js:953:20) at SMTPConnection._onData (/snapshot/cicada/node_modules/nodemailer/lib/smtp-connection/index.js:755:14) at TLSSocket. (/snapshot/cicada/node_modules/nodemailer/lib/smtp-connection/index.js:193:44) at TLSSocket.emit (node:events:527:28) at addChunk (node:internal/streams/readable:315:12) at readableAddChunk (node:internal/streams/readable:289:9) at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
> 
> 一定要配置 qq 邮箱和对应的密码？为什么使用必须登录 qq 邮箱？

你可能需要去了解一下 smtp 协议, `emailHost`/`emailUser`/`emailPass` 这三个配置项是为 smtp 设置的

**Comment by ferocknew** [comment]
> > [14:31:17.602] catch error by catcher Error: Invalid login: 535 Login Fail. Please enter your authorization code to login. More information in http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256 at SMTPConnection._formatError (/snapshot/cicada/node_modules/nodemailer/lib/smtp-connection/index.js:790:19) at SMTPConnection._actionAUTHComplete (/snapshot/cicada/node_modules/nodemailer/lib/smtp-connection/index.js:1548:34) at SMTPConnection. (/snapshot/cicada/node_modules/nodemailer/lib/smtp-connection/index.js:546:26) at SMTPConnection._processResponse (/snapshot/cicada/node_modules/nodemailer/lib/smtp-connection/index.js:953:20) at SMTPConnection._onData (/snapshot/cicada/node_modules/nodemailer/lib/smtp-connection/index.js:755:14) at TLSSocket. (/snapshot/cicada/node_modules/nodemailer/lib/smtp-connection/index.js:193:44) at TLSSocket.emit (node:events:527:28) at addChunk (node:internal/streams/readable:315:12) at readableAddChunk (node:internal/streams/readable:289:9) at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
> > 一定要配置 qq 邮箱和对应的密码？为什么使用必须登录 qq 邮箱？
> 
> 你可能需要去了解一下 smtp 协议, `emailHost`/`emailUser`/`emailPass` 这三个配置项是为 smtp 设置的



我的意思是，这个应用的使用，必须登录 smtp 成功？这应用会对外发邮件？

**Comment by mebtte** [comment]
@ferocknew 会发送登录验证码到用户邮箱
