### ISSUE TITLE
手机播放时出错

### ISSUE THREAD

**Issue by guxinjian666** [mebtte/cicada#85]
iPhone8,桌面模式播放器无法工作，弹出"播放器发生错误，N秒后自动播放下一首。

**Comment by mebtte** [comment]
网络错误或者播放浏览器不支持的音乐格式时会报该错误, 你可以验证一下该音乐是否可以直接在 Safari 上播放. 此外, PWA 在 Safari 上支持度非常差, 不建议在 Safari 上使用.
