### ISSUE TITLE
关闭shell服务自动关闭

### ISSUE THREAD

**Issue by shllwxr** [mebtte/cicada#86]
shell执行完命令后关闭shell，cicada服务就终止了，请问是什么原因？

**Comment by mebtte** [comment]
你需要创建一个后台运行的服务, Linux 常用的有:
1. systemd
2. nohup
3. supervisor

或者使用 docker 托管

**Comment by shllwxr** [comment]
感谢，已经使用systemd创建了后台启动服务。
